apiVersion: 1

contactPoints:
  - orgId: 1
    name: Telegram Loyalty
    receivers:
      - uid: telegram-loyalty-bot
        type: telegram
        settings:
          bottoken: "${BOT_TOKEN}"
          chatid: "414691661"
          parseMode: "HTML"
        disableResolveMessage: false
